---
- hosts: all
  become: true
  tasks:
  - name: Installing Apache and php
    package:
      name:
        -  "{{apache_package}}"
        - "{{php_package}}"
      state: latest
      update_cache: yes

