---
- hosts: all
  become: true
  tasks:
  - name: Installing Apache two
    apt:
      name:
        -  apache2
        -  libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

