---
- hosts: all
  become: true
  tasks:
  - name: Update repo index
    apt: 
      update_cache: yes
  - name: Install apache2 pakcage
    apt:
      name: apache2
		when: ansible_distribution == ["Debian","Ubuntu"]

  - name: Add php support for apache
    apt:
      name: libapache2-mod-php
		when: ansible_distribution == ["Debian","Ubuntu"]
