---
- hosts: all
  become: true
  tasks:
  - name: Uinstall apache2 and php package
    apt:
      update_cache: yes
      name: apache2,libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"

