--- 
- hosts: all
  become: true
  pre_tasks:
    - name: update cache on ubuntu servers
       apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: update cache on Fedora servers
       dnf:
         update_cache: yes
      when: ansible_distribution == "Fedora"
 
- hosts: all
  become: true
  roles:
   - base

- hosts: workstations
  become: true
  roles:
   - workstations

- hosts: web_servers
  become: true
  roles:
   - web_servers

- hosts: db_servers 
  become: true
  roles:
   - db_servers
- hosts: file_servers
  become: true
  roles:
    - file_servers


