---
- hosts: all
  become: true
  tasks:
    - name: updating cache on ubuntu servers
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"
      
    - name: update cache on arch servers
      dnf: 
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Fedora"
    
