- name: install apache and php packages
  tags: apache,httpd,php
  package:       
        name:
           - "{{ apache_package_name }}"
           - "{{ php_package_name }}"
        state: latest

- name: start and enable apache service
  tags: apache,httpd
  service: 
        name: "{{ apache_service }}"
        state: started
        enabled: yes

- name: change email-address for admin
  tags: apache,centos,httpd
  lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin someone@something.net
  when: ansible_distribution == "Fedora" 
  notify: restart_apache

- name: copy default html file for site
  tags: apache2,apache, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

