- name: add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYhMXIQ2jO78sKl/UxP9ClndikUGyoSE6tumwwXL58bOx/+krteUnuV9rgaN/1TX8mAsInw12gKJwax/qYBtshcDyNwywGUebBTRk71gLt6PqczLzSKRonRPvwN8k3d2Lxrhwf1EN3PqG/tmnkNUqolVc7k6rXCUNIEFqt6wQZoNVhd5+O6pT7x0wxzYnVDGiJZiG+g7/QVm0nMcBZhSaGr6KiUKfmexfr8lD01f7StdZCJWN+fdiimfyKzMDbxHcAxZXyA0VdS2h2//tQ+zmH8F1e4VDMsX65UyZWJZieFgSJUnk4O9wThWLc1klKruumbmsI1E47/gsGAndRTYHk4cV8j4MiExpB0Gjs5JmwsfBmqEM9Y7wzb3epVHRXqeOQT+q+ozr7CgH2QmO1WtucRRtDM5XxDTDIUAF5syOygQlE9/y1JlKOaAoIJtccl/g4rWQa0mh1cFjJh0J0K4O4SMDF/IAkhKWQhgPGE0V0mk8BMrp5xwp9YUnYFQt9Z3U= ansible@main-server" 

- name: generate ssh_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd

